### PR TITLE
seperated payload to include metadata_url

### LINKED ISSUE #14: Add optional original metadata path

### PR DESCRIPTION
**Pull request by james-hinton**
fixes #14 

this change was added for a requirement of a specific metadata parser - https://github.com/SpatialDays/stac-proprietary-parsers/blob/master/os_rgbi_parser.py#L62

### CODE REVIEW

**Review by ivica3730k — APPROVED** [review]

**Comment by ivica3730k** [comment]
Just for future reference, pytest and unittests are really a unit-testing frameworks, where you are supposed to test each single public function of your code, and not the whole app endpoint(that would be something like an integration test, not a unit test).

If we are going to continue testing it like this, we could get our pytest/unittest to start a server that you are testing against in a new thread using the threading module. Then we don't depend on the actual server for the test running(which will make it much easier for testing on GitHub actions).

Just food for thoughts @mountaincharlie @james-hinton

**Comment by james-hinton** [comment]
But we don't test against the actual server?

https://github.com/SpatialDays/stac-generator/blob/staging/app/tests/test_stac.py#L3

**Comment by james-hinton** [comment]
Also the code isn't using unittest? 

Lastly, please find me the reference that pytest is solely a unit testing framework.

**Comment by ivica3730k** [comment]
Apologies "Pytest is a Python testing framework that originated from the PyPy project. It can be used to write various types of software tests, including unit tests, integration tests, end-to-end tests, and functional tests."

Nevermind, the late-night GitHub comment cleaning didn't bring out the best of me

**Pull request merged**
